name: styletransfer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.8
  - pandas=0.24.2
  - numpy=1.16.2
  - scipy=1.2.1
  - tensorflow=1.10.0
  - jupyter=1.0.0
  - pytest=4.3.1
  - matplotlib=3.0.3
  - pillow=5.4.1